// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: eth.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Number        uint64                 `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockId) Reset() {
	*x = BlockId{}
	mi := &file_eth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockId) ProtoMessage() {}

func (x *BlockId) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockId.ProtoReflect.Descriptor instead.
func (*BlockId) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{0}
}

func (x *BlockId) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BlockId) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type GetBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       *BlockId               `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	IsFull        bool                   `protobuf:"varint,2,opt,name=is_full,json=isFull,proto3" json:"is_full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_eth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{1}
}

func (x *GetBlockRequest) GetBlockId() *BlockId {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *GetBlockRequest) GetIsFull() bool {
	if x != nil {
		return x.IsFull
	}
	return false
}

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_eth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{2}
}

func (x *DataResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetBlockTransactionCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockTransactionCountResponse) Reset() {
	*x = GetBlockTransactionCountResponse{}
	mi := &file_eth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockTransactionCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockTransactionCountResponse) ProtoMessage() {}

func (x *GetBlockTransactionCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockTransactionCountResponse.ProtoReflect.Descriptor instead.
func (*GetBlockTransactionCountResponse) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlockTransactionCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TransactionId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionId) Reset() {
	*x = TransactionId{}
	mi := &file_eth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionId) ProtoMessage() {}

func (x *TransactionId) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionId.ProtoReflect.Descriptor instead.
func (*TransactionId) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionId) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type GetTransactionByIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       *BlockId               `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	TxIndex       uint32                 `protobuf:"varint,2,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionByIndexRequest) Reset() {
	*x = GetTransactionByIndexRequest{}
	mi := &file_eth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByIndexRequest) ProtoMessage() {}

func (x *GetTransactionByIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByIndexRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionByIndexRequest) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransactionByIndexRequest) GetBlockId() *BlockId {
	if x != nil {
		return x.BlockId
	}
	return nil
}

func (x *GetTransactionByIndexRequest) GetTxIndex() uint32 {
	if x != nil {
		return x.TxIndex
	}
	return 0
}

type GetTraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId *TransactionId         `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceRequest) Reset() {
	*x = GetTraceRequest{}
	mi := &file_eth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceRequest) ProtoMessage() {}

func (x *GetTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceRequest.ProtoReflect.Descriptor instead.
func (*GetTraceRequest) Descriptor() ([]byte, []int) {
	return file_eth_proto_rawDescGZIP(), []int{6}
}

func (x *GetTraceRequest) GetTransactionId() *TransactionId {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

func (x *GetTraceRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_eth_proto protoreflect.FileDescriptor

const file_eth_proto_rawDesc = "" +
	"\n" +
	"\teth.proto\x12\x03rpc\"5\n" +
	"\aBlockId\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x04R\x06number\"S\n" +
	"\x0fGetBlockRequest\x12'\n" +
	"\bblock_id\x18\x01 \x01(\v2\f.rpc.BlockIdR\ablockId\x12\x17\n" +
	"\ais_full\x18\x02 \x01(\bR\x06isFull\"\"\n" +
	"\fDataResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"8\n" +
	" GetBlockTransactionCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"#\n" +
	"\rTransactionId\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"b\n" +
	"\x1cGetTransactionByIndexRequest\x12'\n" +
	"\bblock_id\x18\x01 \x01(\v2\f.rpc.BlockIdR\ablockId\x12\x19\n" +
	"\btx_index\x18\x02 \x01(\rR\atxIndex\"b\n" +
	"\x0fGetTraceRequest\x129\n" +
	"\x0etransaction_id\x18\x01 \x01(\v2\x12.rpc.TransactionIdR\rtransactionId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index2\xb5\x04\n" +
	"\x03Eth\x123\n" +
	"\bGetBlock\x12\x14.rpc.GetBlockRequest\x1a\x11.rpc.DataResponse\x12O\n" +
	"\x18GetBlockTransactionCount\x12\f.rpc.BlockId\x1a%.rpc.GetBlockTransactionCountResponse\x12=\n" +
	"\x14GetTransactionByHash\x12\x12.rpc.TransactionId\x1a\x11.rpc.DataResponse\x12M\n" +
	"\x15GetTransactionByIndex\x12!.rpc.GetTransactionByIndexRequest\x1a\x11.rpc.DataResponse\x12>\n" +
	"\x15GetTransactionReceipt\x12\x12.rpc.TransactionId\x1a\x11.rpc.DataResponse\x123\n" +
	"\x10GetBlockReceipts\x12\f.rpc.BlockId\x1a\x11.rpc.DataResponse\x12=\n" +
	"\x14GetTransactionTraces\x12\x12.rpc.TransactionId\x1a\x11.rpc.DataResponse\x121\n" +
	"\x0eGetBlockTraces\x12\f.rpc.BlockId\x1a\x11.rpc.DataResponse\x123\n" +
	"\bGetTrace\x12\x14.rpc.GetTraceRequest\x1a\x11.rpc.DataResponseB\aZ\x05.;rpcb\x06proto3"

var (
	file_eth_proto_rawDescOnce sync.Once
	file_eth_proto_rawDescData []byte
)

func file_eth_proto_rawDescGZIP() []byte {
	file_eth_proto_rawDescOnce.Do(func() {
		file_eth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eth_proto_rawDesc), len(file_eth_proto_rawDesc)))
	})
	return file_eth_proto_rawDescData
}

var file_eth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_eth_proto_goTypes = []any{
	(*BlockId)(nil),                          // 0: rpc.BlockId
	(*GetBlockRequest)(nil),                  // 1: rpc.GetBlockRequest
	(*DataResponse)(nil),                     // 2: rpc.DataResponse
	(*GetBlockTransactionCountResponse)(nil), // 3: rpc.GetBlockTransactionCountResponse
	(*TransactionId)(nil),                    // 4: rpc.TransactionId
	(*GetTransactionByIndexRequest)(nil),     // 5: rpc.GetTransactionByIndexRequest
	(*GetTraceRequest)(nil),                  // 6: rpc.GetTraceRequest
}
var file_eth_proto_depIdxs = []int32{
	0,  // 0: rpc.GetBlockRequest.block_id:type_name -> rpc.BlockId
	0,  // 1: rpc.GetTransactionByIndexRequest.block_id:type_name -> rpc.BlockId
	4,  // 2: rpc.GetTraceRequest.transaction_id:type_name -> rpc.TransactionId
	1,  // 3: rpc.Eth.GetBlock:input_type -> rpc.GetBlockRequest
	0,  // 4: rpc.Eth.GetBlockTransactionCount:input_type -> rpc.BlockId
	4,  // 5: rpc.Eth.GetTransactionByHash:input_type -> rpc.TransactionId
	5,  // 6: rpc.Eth.GetTransactionByIndex:input_type -> rpc.GetTransactionByIndexRequest
	4,  // 7: rpc.Eth.GetTransactionReceipt:input_type -> rpc.TransactionId
	0,  // 8: rpc.Eth.GetBlockReceipts:input_type -> rpc.BlockId
	4,  // 9: rpc.Eth.GetTransactionTraces:input_type -> rpc.TransactionId
	0,  // 10: rpc.Eth.GetBlockTraces:input_type -> rpc.BlockId
	6,  // 11: rpc.Eth.GetTrace:input_type -> rpc.GetTraceRequest
	2,  // 12: rpc.Eth.GetBlock:output_type -> rpc.DataResponse
	3,  // 13: rpc.Eth.GetBlockTransactionCount:output_type -> rpc.GetBlockTransactionCountResponse
	2,  // 14: rpc.Eth.GetTransactionByHash:output_type -> rpc.DataResponse
	2,  // 15: rpc.Eth.GetTransactionByIndex:output_type -> rpc.DataResponse
	2,  // 16: rpc.Eth.GetTransactionReceipt:output_type -> rpc.DataResponse
	2,  // 17: rpc.Eth.GetBlockReceipts:output_type -> rpc.DataResponse
	2,  // 18: rpc.Eth.GetTransactionTraces:output_type -> rpc.DataResponse
	2,  // 19: rpc.Eth.GetBlockTraces:output_type -> rpc.DataResponse
	2,  // 20: rpc.Eth.GetTrace:output_type -> rpc.DataResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_eth_proto_init() }
func file_eth_proto_init() {
	if File_eth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eth_proto_rawDesc), len(file_eth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eth_proto_goTypes,
		DependencyIndexes: file_eth_proto_depIdxs,
		MessageInfos:      file_eth_proto_msgTypes,
	}.Build()
	File_eth_proto = out.File
	file_eth_proto_goTypes = nil
	file_eth_proto_depIdxs = nil
}
